name: edaj
favicon: null
layout_spectrum: 0.33504665340296924
typography_spectrum: 0.7231145042460412
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050704'
    - '#d8adda'
    - '#6f6d83'
    - '#e838ae'
    - '#0ba4dd'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
